spring:
  application:
    name: WebClient_Factory

springdoc:
  swagger-ui:
    enabled: true

provider:
  baseUrl: https://jsonplaceholder.typicode.com
  token: ----

circuitBreaker:
  timeoutDuration: 60000
  failureCount: 3