name: CICD

on:
  pull_request:
    branches: [ deploy-to-ec2 ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unit Tests with Maven
        run: mvn test -Punit-test
  build:
    name: Build
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t  ${{ secrets.USERNAME }}/webclient-factory:${{ github.sha }} .
      - name: Push docker image
        run: docker push ${{ secrets.USERNAME }}/webclient-factory:${{ github.sha }}
  integration-test:
    name: Integration Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Integration Tests with Maven
        run: mvn test -Pintegration-test
  deploy:
    name: Deploy
    needs: integration-test
    runs-on: [aws-ec2-sandbox]
    steps:
      - name: Pull the latest image from DockerHub
        run: docker pull ${{ secrets.USERNAME }}/webclient-factory:${{ github.sha }}
      - name: Run the container
        run: docker run -d -p 8080:8080 --name webclient-factory-container-:${{ github.sha }} ${{ secrets.USERNAME }}/webclient-factory:${{ github.sha }}