name: CICD

on:
  push:
    branches: [ deploy-to-ec2 ]
  pull_request:
    branches: [ deploy-to-ec2 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t  ${{ secrets.USERNAME }}/webclient-factory .
      - name: Push docker image
        run: docker push ${{ secrets.USERNAME }}/webclient-factory:latest

  deploy:
    name: Deploy
    needs: build
    runs-on: [aws-ec2-sandbox]
    steps:
      - name: Pull the latest image from DockerHub
        run: docker pull ${{ secrets.USERNAME }}/webclient-factory:latest
      - name: Delete old container
        run: docker rm -f webclient-factory-container
      - name: Run the container
        run: docker run -d -p 8080:8080 --name webclient-factory-container ${{ secrets.USERNAME }}/webclient-factory






